# Generated by Django 4.2.7 on 2025-06-26 06:58

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('cv_hash', models.CharField(blank=True, max_length=64, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('current_employer', models.CharField(blank=True, max_length=200)),
                ('years_of_experience', models.IntegerField(blank=True, null=True)),
                ('availability', models.CharField(blank=True, max_length=100)),
                ('preferred_contract_type', models.CharField(blank=True, max_length=100)),
                ('preferred_work_arrangement', models.CharField(blank=True, max_length=100)),
                ('expertise_areas', models.TextField(blank=True, help_text='JSON array of expertise areas')),
                ('sectors', models.TextField(blank=True, help_text='JSON array of industry sectors')),
                ('skill_keywords', models.TextField(blank=True, help_text='JSON array of skill keywords')),
                ('linkedin_profile', models.URLField(blank=True)),
                ('website_portfolio', models.URLField(blank=True)),
                ('languages_spoken', models.TextField(blank=True, help_text='JSON array of languages')),
                ('references', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('professional_certifications', models.TextField(blank=True, help_text='JSON array of certifications')),
                ('professional_associations', models.TextField(blank=True, help_text='JSON array of associations')),
                ('publications', models.TextField(blank=True, help_text='JSON array of publications')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_type', models.CharField(blank=True, max_length=10)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_status', models.CharField(default='pending', max_length=50)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['email'], name='resumes_res_email_0bec76_idx'), models.Index(fields=['cv_hash'], name='resumes_res_cv_hash_14f6d4_idx'), models.Index(fields=['first_name', 'last_name'], name='resumes_res_first_n_41de41_idx'), models.Index(fields=['years_of_experience'], name='resumes_res_years_o_19f837_idx'), models.Index(fields=['location'], name='resumes_res_locatio_e37eaf_idx'), models.Index(fields=['timestamp'], name='resumes_res_timesta_7845e4_idx'), models.Index(fields=['processing_status'], name='resumes_res_process_a6e759_idx')],
            },
        ),
    ]
