# Generated by Django 4.2.7 on 2025-06-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='expertise_experience',
            field=models.TextField(blank=True, help_text='JSON object mapping expertise areas to experience duration'),
        ),
        migrations.AddField(
            model_name='resume',
            name='total_experience_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['date_of_birth'], name='resumes_res_date_of_2bdfdf_idx'),
        ),
    ]
