# Generated by Django 4.2.7 on 2025-06-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resume_date_of_birth_resume_expertise_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Hash of resume content to detect identical files', max_length=64),
        ),
        migrations.AddField(
            model_name='resume',
            name='file_creation_date',
            field=models.DateTimeField(blank=True, help_text='File modification date from metadata (when file was last changed)', null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='person_soft_id',
            field=models.CharField(blank=True, db_index=True, help_text='Soft identifier for person (name+details based)', max_length=64),
        ),
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['content_hash'], name='resumes_res_content_5eacc7_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['person_soft_id'], name='resumes_res_person__c84e58_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['file_creation_date'], name='resumes_res_file_cr_eb85d1_idx'),
        ),
    ]
