# Generated by Django 4.2.7 on 2025-07-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_add_duplicate_detection_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='expertise_details',
            field=models.TextField(blank=True, help_text='JSON object mapping expertise areas to detailed information from resume'),
        ),
    ]
