# Generated by Django 4.2.7 on 2025-07-13 06:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_resume_expertise_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('duration_months', models.IntegerField(blank=True, null=True)),
                ('responsibilities', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('skills_used', models.TextField(blank=True, help_text='JSON array of skills used in this role')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='resumes.resume')),
            ],
            options={
                'ordering': ['-start_date', '-end_date'],
                'indexes': [models.Index(fields=['country'], name='resumes_wor_country_cd5c4b_idx'), models.Index(fields=['company_name'], name='resumes_wor_company_c4c989_idx'), models.Index(fields=['start_date'], name='resumes_wor_start_d_146dcd_idx'), models.Index(fields=['end_date'], name='resumes_wor_end_dat_e08686_idx')],
            },
        ),
    ]
