# Generated by Django 4.2.7 on 2025-07-16 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0006_delete_workexperience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='expertise_experience',
        ),
    ]
